### PR TITLE
add instructions a la noah

### PR DESCRIPTION
**Pull request by staccDOTsol**
Devs will sometimes want to chain sets of instructions; this PR allows them to do so in the matches program.

Can repeat for additional programs as necessary.

### CODE REVIEW

**Review by bhgames — CHANGES_REQUESTED** [review]
Why not just call matchProgramObject.instructions.methodYouWant() directly instead of this whole extra copy/paste method at the top level object? Seems pointless, and breaks the pattern that anchor itself uses.

**Comment by staccDOTsol** [comment]
instructions isn't exposed can check again why, yet i did try that and forget what the error was but it wasnt the usual missing export scope thingy

**Comment by long-banana** [comment]
If you're interested in being able to chain the instructions, this is the approach we are working to move the client toward.

https://github.com/raindrops-protocol/raindrops/blob/master/js/src/instructions/namespace.ts

https://github.com/raindrops-protocol/raindrops/commit/34fd203e8c7be5bb5f8cc9eaa79e84c08cef1ba6

**Comment by staccDOTsol** [comment]
Cheers  @long-banana 

btw I am all-in banana

**Pull request closed without merging**
